### ISSUE TITLE
Talk To Us: Missing text require as per design. Also please add ( * ) sign to indicate the fields that are required.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Facet-Engineering#4]
![4](https://cloud.githubusercontent.com/assets/18256652/14373639/c2d2c0aa-fd7e-11e5-9a0e-ed3cf861f7d8.png)

**Comment by judetitan** [comment]
Aside from "*Text Required" in the design which cannot be applied to plugin restrictions, other concerns where fixed
