### ISSUE TITLE
Leadins: Icon and "Find Out More" moves up which makes the icon clipped while removing leadin text title.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Facet-Engineering#6]
Expected: Icon and "Find Out More" should remain on its original position.
![6](https://cloud.githubusercontent.com/assets/18256652/14374989/fde79962-fd8e-11e5-8119-f0e3f9b13b64.png)

**Comment by judetitan** [comment]
added condition if title is empty the icon will not also show and fixed issues with the content position
