### ISSUE TITLE
Leadin: As per project scope "On leadin hover display title, content and read more link", when verified at the frontend there's no content seen.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Facet-Engineering#7]
Note: This is just to clarify what is the correct expected behavior of this.
![7](https://cloud.githubusercontent.com/assets/18256652/14375297/82a606c2-fd92-11e5-972c-c3419abb1fd4.png)

**Comment by judetitan** [comment]
there were no contents placed in the ACF Leadins Section Tab > Leadin Content Text
