### ISSUE TITLE
Home - OUR WORK section: Clicking "View All" button will open Gallery page, as per design "Clicking 'view all' will expand the section to show all images.". This is just to clarify which of these behavior are expected correct.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Facet-Engineering#9]
![9](https://cloud.githubusercontent.com/assets/18256652/14376080/0070af2a-fd99-11e5-93c9-796e44cc88da.png)

**Comment by judetitan** [comment]
the button was changed to link on gallery page because it has the same functionality and usage as the gallery page to avoid redundancy.

**Comment by iteano** [comment]
Need to update project scope for this functionality.
